name: LostInTranslations
options:
  bundleIdPrefix: com.skala.lostintranslations
settings:
  base:
    MACOSX_DEPLOYMENT_TARGET: 14.0
    SWIFT_VERSION: 6.2
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
    DEAD_CODE_STRIPPING: YES
    ENABLE_USER_SCRIPT_SANDBOXING: YES
    STRING_CATALOG_GENERATE_SYMBOLS: YES
packages: {}
targets:
  LostInTranslations:
    type: application
    platform: macOS
    deploymentTarget: 14.0
    sources:
      - path: LostInTranslations
        excludes:
          - Resources
          - LostInTranslations.icon
    resources:
      - path: LostInTranslations/Resources
      - path: LostInTranslations/Resources/LostInTranslations.icon
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.skala.lostintranslations.app
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        ASSETCATALOG_COMPILER_APPICON_NAME: LostInTranslations.icon
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: FWXSV2MP8Z
        PROVISIONING_PROFILE_SPECIFIER: ""
        CODE_SIGN_ENTITLEMENTS: LostInTranslations/LostInTranslations.entitlements
        DEAD_CODE_STRIPPING: YES
        INFOPLIST_KEY_CFBundleDisplayName: "Lost in Translations"
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.utilities"
    info:
      path: LostInTranslations/Info.plist
      properties:
        CFBundleDisplayName: "Lost in Translations"
        LSUIElement: false
        NSHumanReadableCopyright: "Copyright © 2026"
  LostInTranslationsTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: 14.0
    sources:
      - path: LostInTranslationsTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.skala.lostintranslations.LostInTranslationsTests
    dependencies:
      - target: LostInTranslations

schemes:
  LostInTranslations:
    build:
      targets:
        LostInTranslations: [run, test, profile, analyze, archive]
    test:
      targets:
        - LostInTranslationsTests
  LostInTranslations (Mocked):
    build:
      targets:
        LostInTranslations: [run, test, profile, analyze, archive]
    test:
      targets:
        - LostInTranslationsTests
    run:
      commandLineArguments:
        "-UseMockProvider": true
